### ISSUE TITLE
Documentation missing information

### ISSUE THREAD

**Issue by jorgemmsilva** [revolist/revogrid-react#1]
Hi, RevoGrid looks cool, and I'm looking to experiment with it. 

However, just copying your example from the docs: https://revolist.github.io/revogrid.demo.js/?path=/docs/docs-frameworks-react--page

doesn't yield any result: https://codesandbox.io/s/muddy-dawn-jn9vp?file=/src/Grid.js

It should be clear that we need to execute `defineCustomElements` for the component to work:

```
import { defineCustomElements } from '@revolist/revogrid/loader';
defineCustomElements(); // let browser know new component registered
```

**Comment by SolidZORO** [comment]
Yes, I have the same problem, It took some time to get results. Maybe you could improve the React docs.

**Comment by revolist** [comment]
Sure, will be done by the end of the week.
Thank you for contacting here.

**Comment by revolist** [comment]
@SolidZORO , @jorgemmsilva thank you for this notice.
Documentation has been improved for React integration. Everything else works almost equal everywhere.
https://revolist.github.io/revogrid/guide/framework.react.overview.html

If you face any problem please contact us with no hesitation.
