### ISSUE TITLE
Custom cell renderers written in React

### ISSUE THREAD

**Issue by jorgemmsilva** [revolist/revogrid-react#2]
Hi, is there a straightforward way to use React components as `cellTemplates`?

or are we limited to vanilla html elements / web-components as in the docs?:
https://revolist.github.io/revogrid/guide/cell.renderer.html

---

I was able to work around this by doing the following:

```jsx
  class TestElem extends HTMLElement {
    connectedCallback() {
      const mountPoint = document.createElement('span')
      this.attachShadow({ mode: 'open' }).appendChild(mountPoint)
      const value = this.childNodes[0].data
      ReactDOM.render(<SomeComponent value={value}/>, mountPoint)
    }
  }

  customElements.define('test-elem', TestElem)
```

and if I need access to a redux store, ContextAPI, or other it is possible to create something like this:

```jsx
const registerComponent = (store) => {
  class TestElem extends HTMLElement {
    connectedCallback() {
      const mountPoint = document.createElement('span')
      this.attachShadow({ mode: 'open' }).appendChild(mountPoint)
      const value = this.childNodes[0].data
      ReactDOM.render(
        <Provider store={store}>
          <SomeComponent value={value}/>
        </Provider>,
        mountPoint,
      )
    }
  }
  customElements.define('test-elem', TestElem)
}

// and when the store is created:
...
registerComponent(store)
...
```

however, this is not ergonomic at all 😕 

do you have plans to facilitate the implementation of react components as cell/header templates?

---

I think something like this could be a good way to do it, where the web-component definition would be abstracted from the user:
```jsx

  <RevoGrid
    columns={columns}
    source={data}
    customComponents={{
        'test-elem': TestElem,
        'my-header': MyHeader
    }}
    componentWrappers={
        [StoreWrapper, SomeContext.Provider, etc]
    }
  />
```

what do you think?

**Comment by jorgemmsilva** [comment]
FYI ended up customizing the web-components creation further (skipping the shadow DOM, as I wanted to re-use styles), also fixes the fact that the implementation above wouldn't update when the data had changed.

```
  customElements.define(componentTag,
    class extends HTMLElement {
      static get observedAttributes() {
        return ['value']
      }

      disconnectedCallback() {
        ReactDOM.unmountComponentAtNode(this)
      }

      connectedCallback() {
        this.render()
      }

      attributeChangedCallback(name, oldValue, newValue) {
        this.render()
      }

      render() {
        if (!this.isConnected) {
          return
        }
        const value = _get(this, 'attributes.value.value', '')
        ReactDOM.render(<Component value={value} data={data} />, this)
      }
    })
```

usage looks like this:
```
createElement( webComponentName, { value: props.model[props.prop] })
```

**Comment by revolist** [comment]
@jorgemmsilva it's strongly recommended to use web component VNode elements for better performance, usually, projects grow too fast and it's too late then to refactor it back. 
But we've provided some more information on how React components can be integrated inside of original DOM in web components. 

https://revolist.github.io/revogrid/guide/framework.react.component.html
You can even create your own provider around it if you wish, we'll be able to populate if needed.

Thank you for your notices.

**Comment by jorgemmsilva** [comment]
Thanks for the reply @revolist, but after trying the implementation you made available in the docs, I can tell you the performance impact is magnitudes worse than my suggestion. The result is not even comparable really :/
