### ISSUE TITLE
use defineCustomElements to import *.entry.js in Vite is 404 

### ISSUE THREAD

**Issue by zicokuo** [revolist/revogrid-react#3]
I want to use revoGrid in JSX.Component and Vite to build something,

it had got a 404 error, like this:

![image](https://user-images.githubusercontent.com/4969958/112783593-41432600-9082-11eb-8931-6c2b843fbc12.png)

I think because Vite had rewrite defineCustomElements' import url path ...

Can help me to fix it?

**Comment by revolist** [comment]
Hello, try this sample as a starter
https://github.com/revolist/vue3-revolist-vite

or are you looking for vite without vue?
please provide your own minimal sample we can look at it

**Comment by revolist** [comment]
Closed because of inactivity.
