### ISSUE TITLE
vite can't be load the entry file

### ISSUE THREAD

**Issue by zeekrs** [revolist/revogrid-react#6]
vite console   Unrestricted file system access to "/node_modules/.vite/revo-grid_11.entry.js"

**Comment by JulienGrv** [comment]
Hi, RevoGrid does not work with [Vite](https://vitejs.dev/) + React. I tried to tweak Vite but no luck so far. I looked at your Vite + Vue project but it's using an older version of Vite so not really the solution I am looking for. This is the console log:

```
index-42c84e7c.js:1 GET http://localhost:3000/node_modules/.vite/revo-grid_11.entry.js net::ERR_ABORTED 404 (Not Found)
index-42c84e7c.js:1 TypeError: Failed to fetch dynamically imported module: http://localhost:3000/node_modules/.vite/revo-grid_11.entry.js undefined
```

**Comment by JulienGrv** [comment]
Ok I got it working with the help of <https://github.com/revolist/revogrid/blob/master/docs/custom.element.md>:

```typescript
import { defineCustomElements } from "@revolist/revogrid/custom-element";
defineCustomElements();
```

I was trying to import { defineCustomElements } from "@revolist/revogrid/loader" before which does not work.

**Comment by martindemello** [comment]
@JulienGrv thank you!! that worked like a charm.
